### ISSUE TITLE
Transfer.sh not in sync with this repository

### ISSUE THREAD

**Issue by davidindra** [dutchcoders/transfer.sh-web#15]
Hello,
I see that https://transfer.sh is not synchronised with this repository sources. Why is it like that? :)
Thanks for your response,
David

**Comment by aspacca** [comment]
hello @davidindra 
https://transfer.sh is the hosted service part of the project. both were originally created and maintained by @nl5887 and there were no update for a long time until I sent a pull request on the other repository (https://github.com/dutchcoders/transfer.sh) and offered to continue supporting the codebase. so the codebase is now supported, by me, but the hosting is still owned by the original owner. last time I heard him he told me he wanted to keep it in sync with the code, but I have no info about him since few month (we don't know each other personally)

hope this answer you question
